# ---------------- #
#   Main Configs   #
# ---------------- #
## 这些变量都是site级别的，使用：{{ site.location }}
baseurl:
url: https://coderwing.github.io
date_format: "ordinal"
title: 宋旭东
subtitle: "日拱一卒无有尽,功不唐捐终入海"
description: "宋旭东的个人博客"
keywords: 宋旭东,coderwing,Wator
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 宋旭东
organization:
organization_url:
github_username: coderwing
location: Beijing, China
email: coderwing@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: coderwing/coderwing.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: coderwing
    repo: blog-comments-Repo
    oauth:
        client_id: e04660e5bd22b957e161
        client_secret: 9b019f5fbda5bc4dc1e298f4f0d1c36ff247363f
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: coderwing
    repo: blog-comments-Repo
    clientID: e04660e5bd22b957e161
    clientSecret: 9b019f5fbda5bc4dc1e298f4f0d1c36ff247363f
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
